<?php
/**
 * @var \PayPro\Przelewy24\Block\Customer\CardRenderer $block
 * @var \Magento\Framework\Escaper $escaper
 */

use Magento\Vault\Api\Data\PaymentTokenInterface;

$ccNumberView = $escaper->escapeHtml($block->getNumberLast4Digits());
?>
<tr>
    <td data-th="<?= $escaper->escapeHtml(__('Card Number')) ?>" class="col card-number">
        <span><?= $escaper->escapeHtml(__('ending')) ?></span> <?= /* @noEscape */ $ccNumberView ?>
    </td>
    <td data-th="<?= $escaper->escapeHtml(__('Expiration Date')) ?>" class="col card-expire">
        <?= $escaper->escapeHtml($block->getExpDate()) ?>
    </td>
    <td data-th="<?= $escaper->escapeHtml(__('Type')) ?>" class="col card-type card-type--przelewy24">
        <img src="<?= /* @noEscape */ $block->getIconUrl() ?>"
             width="<?= /* @noEscape */ $block->getIconWidth() ?>"
             height="<?= /* @noEscape */ $block->getIconHeight() ?>"
        >
    </td>
    <td data-th="<?= $escaper->escapeHtml(__('Actions')) ?>" class="col actions">
        <form
            class="form"
            action="<?= $escaper->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
            method="post"
            >
            <?= $block->getBlockHtml('formkey') ?>
            <input
                name="<?= /* @noEscape */ PaymentTokenInterface::PUBLIC_HASH ?>"
                value="<?= /* @noEscape */ $block->getToken()->getPublicHash() ?>"
                type="hidden"/>
            <button type="submit"
                    class="action delete"
                    data-mage-init='{
                        "Magento_Vault/js/customer_account/deleteWidget":{
                            "type": "popup",
                            "modalClass": "my-credit-cards-popup",
                            "toggleEvent": "click",
                            "title": "<?= $escaper->escapeHtml(__('Delete')) ?>",
                            "content": "Are you sure you want to delete this card: <?=
                                /* @noEscape */ $ccNumberView
                            ?>?"
                        }
                    }'>
                <span><?= $escaper->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
    </td>
</tr>
