<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \PayPro\Przelewy24\ViewModel\PlacementViewModel $viewModel
 * @var \Magento\Framework\Escaper $escaper
 */

use PayPro\Przelewy24\ViewModel\PlacementViewModel;

$viewModel = $block->getViewModel();
$linkUrl = PlacementViewModel::PRZELEWY24_PLACEMENT_LINK_URL;
$imgUrl = PlacementViewModel::PRZELEWY24_PLACEMENT_IMAGE_URL;
?>

<?php if ($viewModel->isPlacementVisibleInOrderView()): ?>
    <div class="przelewy24-placement">
        <a href="<?= $escaper->escapeHtmlAttr($linkUrl) ?>">
            <img src="<?= $escaper->escapeHtmlAttr($imgUrl) ?>" alt="Przelewy24"/>
        </a>
    </div>
<?php endif; ?>
