<?php
/**
 * @var \Magento\Payment\Block\Info $block
 * @var \Magento\Framework\Escaper $escaper
 */
$specificInfo = $block->getSpecificInformation();
$title = $escaper->escapeHtml($block->getMethod()->getTitle());
?>
<dl class="payment-method">
    <dt class="title"><?= /* @noEscape */ $title ?></dt>
    <?php if ($specificInfo): ?>
        <dd class="content">
            <table class="data table">
                <caption class="table-caption"><?= /* @noEscape */ $title ?></caption>
                <?php foreach ($specificInfo as $label => $value): ?>
                    <tr>
                        <th scope="row"><?= $escaper->escapeHtml(__($label)) ?></th>
                        <td>
                            <?= /* @noEscape */ nl2br($escaper->escapeHtml(
                                implode("\n", $block->getValueAsArray($value)),
                                ['a']
                            )) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </dd>
    <?php endif;?>
</dl>
<?= $block->getChildHtml() ?>
