<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="p24-payment-success">
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $escaper->escapeUrl($block->getUrl('/')) ?>">
                <span><?= $escaper->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        </div>
    </div>
</div>
