<?php
/**
 * @var \PayPro\Przelewy24\Block\Customer\BlikRenderer $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<tr>
    <td data-th="<?= $escaper->escapeHtmlAttr(__('Account')) ?>" class="col">
        <span><?= $escaper->escapeHtml(__('Alias for: %1', $block->getTokenEmail())) ?></span>
    </td>
    <td data-th="<?= $escaper->escapeHtmlAttr(__('Type')) ?>" class="col col--przelewy24-blik">
        <img src="<?= $escaper->escapeHtmlAttr($block->getIconUrl()) ?>"
             width="<?= $escaper->escapeHtmlAttr($block->getIconWidth()) ?>"
             height="<?= $escaper->escapeHtmlAttr($block->getIconHeight()) ?>"
             class="blik-token-image"
             alt="BLIK">
    </td>
    <td data-th="<?= $escaper->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
        <form class="form"
              action="<?= $escaper->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
              method="post">
            <?= $block->getBlockHtml('formkey') ?>
            <input name="public_hash"
                   value="<?= $escaper->escapeHtmlAttr($block->getToken()->getPublicHash()) ?>"
                   type="hidden"/>
            <button type="submit"
                    class="action delete"
                    data-mage-init='{
                        "Magento_Vault/js/customer_account/deleteWidget":{
                            "type": "popup",
                            "modalClass": "my-credit-cards-popup",
                            "toggleEvent": "click",
                            "title": "<?= $escaper->escapeHtmlAttr(__('Delete')) ?>",
                            "content": "Are you sure you want to delete this BLIK account?"
                        }
                    }'>
                <span><?= $escaper->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
    </td>
</tr>
