<?php
/**
 * @var \Magento\Payment\Block\Info $block
 * @var \Magento\Framework\Escaper $escaper
 */
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
?>
<?= $escaper->escapeHtml($paymentTitle) ?>{{pdf_row_separator}}

<?php if ($specificInfo = $block->getSpecificInformation()): ?>
    <?php foreach ($specificInfo as $label => $value): ?>
        <?php
        if ($label === \PayPro\Przelewy24\Model\PaymentLink::LABEL) {
            continue;
        }
        ?>
        <?= $escaper->escapeHtml($label) ?>:
        <?= $escaper->escapeHtml(implode(' ', $block->getValueAsArray($value))) ?>
        {{pdf_row_separator}}
    <?php endforeach; ?>
<?php endif;?>

<?= $escaper->escapeHtml(implode('{{pdf_row_separator}}', $block->getChildPdfAsArray())) ?>
